// generated by grok

const sampleData = {
  "projectList": [
    {
      "title": "Build Personal Portfolio Website",
      "description": "Create a responsive portfolio site showcasing my projects, skills, and contact info using React and Tailwind CSS.",
      "dueDate": "2026-05-15",
      "tasks": [
        { "text": "Design wireframes for homepage and project gallery", "checked": true },
        { "text": "Set up React project with Vite and Tailwind", "checked": true },
        { "text": "Implement responsive navigation and hero section", "checked": false },
        { "text": "Add project cards with images and descriptions", "checked": false },
        { "text": "Create contact form with validation", "checked": false },
        { "text": "Deploy to Netlify and test on mobile devices", "checked": false }
      ]
    },
    {
      "title": "Organize Family Vacation",
      "description": "Plan a 7-day trip to Hawaii for the whole family, including flights, accommodations, activities, and budget tracking.",
      "dueDate": "2026-07-01",
      "tasks": [
        { "text": "Research and book round-trip flights for 4 people", "checked": true },
        { "text": "Find and reserve beachfront vacation rental", "checked": false },
        { "text": "Create itinerary with daily activities and restaurants", "checked": false },
        { "text": "Purchase travel insurance and check visa requirements", "checked": false },
        { "text": "Pack suitcases and prepare travel documents", "checked": false },
        { "text": "Set up budget spreadsheet for expenses", "checked": false }
      ]
    },
    {
      "title": "Learn Spanish Conversation",
      "description": "Improve conversational Spanish skills through daily practice, apps, and language exchange to reach intermediate level.",
      "dueDate": "2026-08-30",
      "tasks": [
        { "text": "Complete Duolingo Spanish course basics", "checked": true },
        { "text": "Practice 30 minutes daily with language exchange partner", "checked": true },
        { "text": "Watch 2 Spanish movies with subtitles this month", "checked": false },
        { "text": "Read one Spanish novel and write a summary", "checked": false },
        { "text": "Join local Spanish conversation meetup group", "checked": false },
        { "text": "Take online intermediate Spanish grammar quiz", "checked": false }
      ]
    }
  ]
};

document.cookie = 'projects=' + encodeURIComponent(JSON.stringify(sampleData)) + '; path=/';